Update coverage_report.yml

diff --git a/.github/workflows/coverage_report.yml b/.github/workflows/coverage_report.yml
--- a/.github/workflows/coverage_report.yml
+++ b/.github/workflows/coverage_report.yml
@@ -1,13 +1,11 @@
 name: Add coverage comment on PR
 
-# read-write repo token
-# access to secrets
 on:
   workflow_run:
     workflows: ["Test and lint"]
     types:
       - completed
-
+      
 permissions: {}
 
 jobs:
@@ -16,9 +14,10 @@ jobs:
         contents: read
         pull-requests: write
     runs-on: ubuntu-latest
+    #&& github.repository == github.event.workflow_run.repository.full_name
     if: >
       github.event.workflow_run.event == 'pull_request'
-    steps:
+      steps:
       - name: Download PR number
         uses: actions/download-artifact@v4
         with:
@@ -27,24 +26,57 @@ jobs:
             github-token: ${{ secrets.GITHUB_TOKEN }}
             run-id: ${{ github.event.workflow_run.id }}
       - name: Extract PR number
-        id: pr_number
+        id: extract_pr_number
         run: |
-          ls -a
-          echo "------"
-          ls -a pr_number*
-          echo "PR number is:"
+          echo "Triggering PR number is:"
           cat pr_number/pr_number.txt
-          # store pr number to access it
-          echo "pr_number=$(cat pr_number/pr_number.txt)" >> $GITHUB_ENV
+          # Check that it is only a numeric value in pr_number
+          if ! grep -q '^[0-9]\+$' pr_number/pr_number.txt; then
+            echo "Error: PR number is not numeric"
+            exit 1
+          fi
+          # check that it has at most 6 characters
+          if [ "$(wc -c < pr_number/pr_number.txt)" -gt 6 ]; then
+            echo "Error: PR number is too long"
+            exit 1
+          fi
+          "pr_number=$(cat pr_number/pr_number.txt)" >> $GITHUB_OUTPUT
+      - name: Get PR number from commit SHA
+        id: get_pr
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          SHA="${{ github.event.workflow_run.head_sha }}"
+          REPO="${{ github.repository }}"
+          PR_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+            "https://api.github.com/repos/$REPO/commits/$SHA/pulls" \
+            -H "Accept: application/vnd.github.groot-preview+json")
+          echo "$PR_DATA"
+          PR_NUMBER=$(echo "$PR_DATA" | jq '.[0].number')
+          echo "PR number is $PR_NUMBER"
+          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
       - name: Download coverage report
         uses: actions/download-artifact@v4
         with:
-          pattern: code-coverage-results.md
+          pattern: coverage.xml
           github-token: ${{ secrets.GITHUB_TOKEN }}
           run-id: ${{ github.event.workflow_run.id }}
+      - name: Code Coverage Report
+        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
+        with:
+          filename: coverage.xml
+          badge: true
+          fail_below_min: false
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: true
+          indicators: true
+          output: both
+          thresholds: '80 90'
       - name: Add Coverage PR Comment
         uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728  # v2.9.3
         with:
           recreate: true
           path: code-coverage-results.md
-          number: ${{ env.pr_number }}
+          number: ${{ steps.get_pr.outputs.pr_number }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
